FROM lscr.io/linuxserver/qbittorrent:latest

RUN mkdir -p /config/qBittorrent/ && echo $' \n\
[Preferences]\n\
WebUI\AuthSubnetWhitelist=0.0.0.0/0\n\
WebUI\AuthSubnetWhitelistEnabled=true\n\
WebUI\UseUPnP=false' >> /config/qBittorrent/qBittorrent.conf
