FROM ubuntu:noble

RUN apt-get update -y && \
    apt-get install -y curl iputils-ping libc6 wireguard && \
    curl https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/n/nordvpn-release/nordvpn-release_1.0.0_all.deb --output /tmp/nordrepo.deb && \
    apt-get install -y /tmp/nordrepo.deb && \
    apt-get update -y && \
    apt-get install -y nordvpn${NORDVPN_VERSION:+=$NORDVPN_VERSION} && \
    apt-get remove -y nordvpn-release && \
    apt-get autoremove -y && \
    apt-get autoclean -y && \
    rm -rf \
      /tmp/* \
      /var/cache/apt/archives/* \
      /var/lib/apt/lists/* \
      /var/tmp/*

RUN echo '(nordvpn status | grep "Status: Connected") && exit 0\n\
nordvpn set dns 1.1.1.1 1.0.0.1 || true\n\
nordvpn whitelist add port 8080 || true\n\
nordvpn set killswitch on || true\n\
nordvpn login --token $NORDVPN_TOKEN || true\n\
nordvpn connect\n\
(nordvpn status | grep "Status: Connected") && exit 0\n\
exit 1\n' \
> /connect.sh

RUN chmod +x /connect.sh

ENTRYPOINT [ "nordvpnd" ]
